# Generated by Django 2.0.2 on 2018-04-19 21:09

from django.db import migrations
import finger.models


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', finger.models.UserManager()),
            ],
        ),
    ]
