# Generated by Django 2.0.4 on 2018-06-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0002_auto_20180419_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payed_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ths_claimed_ht',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ths_claimed_vt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ths_verified_ht',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ths_verified_vt',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
