# Generated by Django 2.0.6 on 2018-06-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0004_auto_20180630_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='The members address.', null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.TextField(blank=True, help_text='One or more comments about the member.', null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_parted',
            field=models.DateTimeField(blank=True, help_text='The date of when a member left the club.', null=True, verbose_name='Date parted'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_key',
            field=models.BooleanField(default=False, help_text='If the member has a key to the computer hall.', verbose_name='Has a Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='honourable_member',
            field=models.BooleanField(default=False, help_text='If the member is a Honourable member.', verbose_name='Honourable Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycard_number',
            field=models.PositiveIntegerField(blank=True, help_text="The number of KTH's keycard, used by us to grant members access to the clubroom.", null=True, verbose_name='Keycard Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='kth_account',
            field=models.CharField(blank=True, help_text='The KTH accound name, useful when validating THS membership status.', max_length=255, null=True, verbose_name='KTH account'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='One or several phone numbers to the member.', max_length=255, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='support_member',
            field=models.BooleanField(default=False, help_text='The memeber is an support member, the member has no voting rights.', verbose_name='Support Member'),
        ),
        migrations.AddField(
            model_name='user',
            name='ths_name',
            field=models.CharField(blank=True, help_text='If the member is known by some other name in THS systems, this will override the name when we validates THS membership status.', max_length=255, null=True, verbose_name='THS Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, help_text='An optional title to the member.', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='payed_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The year the member has valid payed membership to.', null=True, verbose_name='Payed Year'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ths_claimed_ht',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The member has claimed to be a THS member for the second half of the specified year.', null=True, verbose_name='THS Claimed Member HT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ths_claimed_vt',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The member has claimed to be a THS member for the fist half of the specified year.', null=True, verbose_name='THS Claimed Member VT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ths_verified_ht',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The member is verified to be a THS member for the second half of the specified year.', null=True, verbose_name='THS Verified Member HT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ths_verified_vt',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The member is verified to be a THS member for the fist half of the specified year.', null=True, verbose_name='THS Verified Member VT'),
        ),
    ]
