# Generated by Django 2.2.16 on 2020-11-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0009_auto_20201115_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='identifier',
            field=models.CharField(default=None, help_text='A unique identifier used to map a fingerweb user to this entry.', max_length=32, null=True, verbose_name='A unique identifier'),
        ),
    ]
