# Generated by Django 2.0.2 on 2018-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180310_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
