# Generated by Django 2.0.2 on 2018-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='longdesc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='shortdesc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
