# Generated by Django 2.2.28 on 2023-10-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0010_member_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
