# Generated by Django 2.2.28 on 2023-10-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finger', '0011_remove_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payed_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='The year the member has valid paid membership to.', null=True, verbose_name='Paid Year'),
        ),
    ]
